### ISSUE TITLE
What can BlockLauncher do in the future?

### ISSUE THREAD

**Issue by XFY9326** [zhuowei/MCPELauncher#1062]
Now official support texture pack in MCPE 0.15.0.The most important reason why we still use BlockLauncher is that the MOD,ModPE and Addons.

In the future,official will support more just like the PC JAVA version.l think it's necessary for BlockLauncher to have a new function.

I suggest that we can have a new kind of package that can contains ModPE,Mod,Addon,Texture pack,Game Worlds and Skins.It's easy for Player who want to play games made by others.

And more,we can develop an APK to encrypt this package.In this way,this package can be only used on BlockLauncher and authors will not be afraid of their Worlds,Mods and so on be stolen.

That is my suggestion.
However my English is not good.If there are any grammar mistakes,please ignore it. :)

**Comment by VickyGaming** [comment]
We still need blocklaucher for the texturepacks!Minecraft is being stingy and you have to buy them and no custom neither :/

**Comment by zedman2000** [comment]
@VickyGaming in the /games/com.mojang folder, create a folder resource_packs
in that folder, extract the texture pack you want to use.  It needs to be 0.15 compatible.  From there you will be able to use the native texture pack menu in Vanilla Minecraft to load that texture pack.
We will still need the TP loading from BL for mods that add new items.  If BL still supports full texture packs, I'll probably load them through BL so I don't have to manage my TP in two places nor worry about extracting them all the time.  I use a custom one where I manually merged 4 TPs together, so a FULL load is important to me and I won't update my TP until I find out if BL does a FULL load or not.
Check www.mcpedl.com there is a good guide on there to setup Vanilla Minecraft with a 0.15 compatible TP.

**Comment by VickyGaming** [comment]
I still don't understand😂😂😂

**Comment by zedman2000** [comment]
@VickyGaming did you look on MCPEDL.COM?
http://mcpedl.com/how-to-install-minecraft-pe-texture-packs-for-android/
I'm not sure I can make it simpler than that.

**Comment by XFY9326** [comment]
@zedman2000
Excuse me, l don't know what is TP loading?
To add a new item's texture, we can use the modpkg.

**Comment by zedman2000** [comment]
@XFY9326 texture pack.  :-)
Textures can come into the game's memory many ways.  Using 0.15 there is now an official way.
Essentially I was saying:
*drop support for FULL texture packs so Zhuowei doesn't waste time on that code - officially it is supported now
*continue/enhance the item textures - as you said, these can be in a modpkg, or .zip as it is now.  I personally like the non-modpkg due to WHEN BL loads the textures my try/catches can cause false triggers.  I also like the NON-modpkg because then the texture pack icons are displayed and you can see them nicely listed.

My point above mostly stems from that Zhuowei should do what ever is easiest to maintain.  The more time he spends on fixing issues due to complex configurations for texture packs, the less time he has to add new features or correct bug fixes as Minecraft PE evolves.  For instance, there are many functions that need constant attention.  I am guessing because while the function name that Zhuowei hooks into does not change, the logic inside does -  which then requires an update to BL to allow the MODPE community to keep using that function.  The more optimized his time is, the better Block Launcher can become!

**Comment by DiegoGTRatty** [comment]
I'll put it in English.

Get a file manager app or connect your phone to a PC with a USB cable.

Next, head over to your games folder. Inside, find the folder that says:

> com.mojang

In there, create a folder named:

> resource_packs

This "resource_packs" folder is where you will move your texture packs. If the texture pack is a .ZIP file (which it most likely is), extract it right in the "resource_packs" folder. Delete the .ZIP once it extracted so you can save a bit of memory.

Now open up Minecraft PE and head to the options. Below the "Third Person View" option, you can choose which texture packs to install. Make sure you move your own texture pack to the right, so the game loads it.

And that should be it. If it doesn't work, then it's probably because the texture pack hasn't been updated to 0.15.x.

**Comment by zedman2000** [comment]
If this is resolved, please close this so Zhouwei does not spend time reading this through only to realize he has taken time to review something he needn't have.  Again, we need to be the best community we can to help him spend MORE time on the guts of BlockLauncher, so that we do NOT spend his time dealing with paperwork.  I'd MUCH rather he fix functions and get a new version of BL out to us, not sit here for 2+ days clicking close on issues that need to be closed.

Thanks!

**Comment by zedman2000** [comment]
@XFY9326 that last message was meant for you.  Sorry, I forgot to tag you to make sure you get an alert.
