### ISSUE TITLE
Block launcher crashes

### ISSUE THREAD

**Issue by TheDarkTStar** [zhuowei/MCPELauncher#1084]
Block launcher crashes whenever I open it. In previous versions of Minecraft pe it workes
My phone is huawei honor 4c
And my Android operating system version is 5.1.1

**Comment by VickyGaming** [comment]
Its because they haven't updated to 0.15.0 -clearly

**Comment by zedman2000** [comment]
If you updated to 0.15:
It has not been updated for 0.15.  It takes time to re-hook into all the functions.  It was stated on Twitter that the author is going to TRY to get it ported for 0.15 by the end of the week.  Please close this issue as it is wasting the author's time.  Instead of porting the program he is spending his time closing issue like this which are just fodder.  Porting the program is going to happen, so again, please close this so you do not waste the author's time.
