### ISSUE TITLE
Black screen then BOOM its crashed .-. HELP PLZ

### ISSUE THREAD

**Issue by EmojiPandazMC** [zhuowei/MCPELauncher#1094]
Hey peeps,
Ok so since I have gotten 0.15.0 and trying to use BlockLauncher, its just come up with a black screen and just CRASHED. Idk whats happening plz help me!!

**Comment by zedman2000** [comment]
It has not been updated for 0.15.  It takes time to re-hook into all the functions.  It was stated on Twitter that the author is going to TRY to get it ported for 0.15 by the end of the week.  Please close this issue as it is wasting the author's time.  Instead of porting the program he is spending his time closing issue like this which are just fodder.  Porting the program is going to happen, so again, please close this so you do not waste the author's time.

**Comment by EmojiPandazMC** [comment]
Ok sorry for the inconvenience I'll close it once I figure out how.... I'm new xD

**Comment by EmojiPandazMC** [comment]
Ok, thats good to know. I'm sorry for the inconvenience, and I'll close it :)
