### ISSUE TITLE
Wont run

### ISSUE THREAD

**Issue by deathrekcuf** [zhuowei/MCPELauncher#1107]
I have a 4g lte and every time i try to open it it tries to run then it takes me back to my home screen. Please fix this bc i really like using the ore spawn mod.

**Comment by zedman2000** [comment]
If you updated to 0.15:
It has not been updated for 0.15. It takes time to re-hook into all the functions. It was stated on Twitter that the author is going to TRY to get it ported for 0.15 by the end of the week. Please close this issue as it is wasting the author's time. Instead of porting the program he is spending his time closing issue like this which are just fodder. Porting the program is going to happen, so again, please close this so you do not waste the author's time.
