### ISSUE TITLE
Crash upon opening

### ISSUE THREAD

**Issue by twinmommy0306** [zhuowei/MCPELauncher#1115]
Crashes when starting on lg GPadF 8.0

**Comment by BandyPlays** [comment]
It needs updating to 0.1.5 or what ever the latest update is just have to wait until it updates

**Comment by Black-DeathPE** [comment]
**Be patient, @zhuowei is busy working on updating BL to support v0.15.0, close this issue.**

**Comment by zedman2000** [comment]
If you updated to 0.15:
It has not been updated for 0.15. It takes time to re-hook into all the functions. It was stated on Twitter that the author is going to TRY to get it ported for 0.15 by the end of the week. Please close this issue as it is wasting the author's time. Instead of porting the program he is spending his time closing issue like this which are just fodder. Porting the program is going to happen, so again, please close this so you do not waste the author's time.
