### ISSUE TITLE
Block launcher update

### ISSUE THREAD

**Issue by Thebeastincarnate** [zhuowei/MCPELauncher#1121]
When will the block launcher update to 0.15.0 pls be faster. I wan to use.

**Comment by Black-DeathPE** [comment]
Patience, he's working on it.

**Comment by zedman2000** [comment]
Adding comments like this slows him down.  Please close this so he does not spend time managing these messages instead of working on BL.

If you updated to 0.15:
It has not been updated for 0.15. It takes time to re-hook into all the functions. It was stated on Twitter that the author is going to TRY to get it ported for 0.15 by the end of the week. Please close this issue as it is wasting the author's time. Instead of porting the program he is spending his time closing issue like this which are just fodder. Porting the program is going to happen, so again, please close this so you do not waste the author's time.
