### ISSUE TITLE
Blocklauncher doenst work

### ISSUE THREAD

**Issue by IronVking** [zhuowei/MCPELauncher#1126]
Hey guys, 

the block launcher and the pro version doenst work.
Any shader pack i try to use the game ofer launcher will crash.

I try 8 different shader mods but no one will working.

LG G5 Android 6

**Comment by IronVking** [comment]
Mcpe 0.14.3 and the Market Version i try.

Block launcher Pro i buy from the Market

**Comment by pawsthehelper** [comment]
If your Minecraft is updated to .15 then they will be fixing this issue by the end of the week hope this helps

**Comment by zedman2000** [comment]
If you updated to 0.15:
It has not been updated for 0.15. It takes time to re-hook into all the functions. It was stated on Twitter that the author is going to TRY to get it ported for 0.15 by the end of the week. Please close this issue as it is wasting the author's time. Instead of porting the program he is spending his time closing issue like this which are just fodder. Porting the program is going to happen, so again, please close this so you do not waste the author's time.
