### ISSUE TITLE
BlockLauncher pro not working in mcpe v0.15.0

### ISSUE THREAD

**Issue by Mark0Tech** [zhuowei/MCPELauncher#1128]
# BlockLauncher Pro is not working with mcpe v0.15.0
It always crashes whenever I run it.
My model is ACER b1-700 running Android 5.1
Please fix this
I can't even run the app.
##### Thanks, and please fix this!
😀

**Comment by pawsthehelper** [comment]
If your Minecraft is updated to .15 then they will be fixing this issue by the end of the week hope this helps

**Comment by zedman2000** [comment]
If you updated to 0.15:
It has not been updated for 0.15. It takes time to re-hook into all the functions. It was stated on Twitter that the author is going to TRY to get it ported for 0.15 by the end of the week. Please close this issue as it is wasting the author's time. Instead of porting the program he is spending his time closing issue like this which are just fodder. Porting the program is going to happen, so again, please close this so you do not waste the author's time.

**Comment by lowjames** [comment]
Plz, close this report because, were spending more time dealing with reports than fixing Blocklauncher.

Thx!
