### ISSUE TITLE
Pro & Free not working for MCPE v.0.15.0.1

### ISSUE THREAD

**Issue by Smasher535** [zhuowei/MCPELauncher#1134]
Everytime i try to open blocklauncher it gives me a black screen and crashes. When i open my filemanager and use 'Manage ModPE-scripts' to open a JavaScript file, it works, i imporyed it but it's still crashing!! FIX IT, i wanna mod 0.15.0.1

___INFO______
Android version: 5.0.1 (Lolipop)
Device: Asus ZenPad 10
Model number: PO1T
I have a INTEL device

**Comment by zedman2000** [comment]
First, I don't think that MCPE runs on Intel right now (I've not been able to get it to run on my x86 based device since 0.14.1).  Second:

If you updated to 0.15:
It has not been updated for 0.15. It takes time to re-hook into all the functions. It was stated on Twitter that the author is going to TRY to get it ported for 0.15 by the end of the week. Please close this issue as it is wasting the author's time. Instead of porting the program he is spending his time closing issue like this which are just fodder. Porting the program is going to happen, so again, please close this so you do not waste the author's time.

**Comment by Smasher535** [comment]
1. MCPE INTEL exists
2. I had BLOCKLAUNCHER in 0.14.0
3. :P

**Comment by zedman2000** [comment]
1. I did not say that it does NOT exist for Intel.  I specifically said that MCPE does not seem to run on Intel right now.  I have an Intel device and it has struggled running vanilla Minecraft since 0.14.1.

2. And you specifically said, " i wanna mod 0.15.0.1".  Since you did not mention ANY other version number, this lead me to believe that you were running on 0.15.

Thank you for closing this, it will help the author not spend time checking issues that have been not only reported 100's of times, but before issues even started posting, he specifically stated he is already working on updating.

**Comment by MhikeiMPC** [comment]
Im sure the OP means MCPE runs on his intel device, and Blocklauncher runs perfectly fine on 0.14.0.
