### ISSUE TITLE
Es startet nicht

### ISSUE THREAD

**Issue by RetrocrafterHD** [zhuowei/MCPELauncher#1156]
Wenn ich versuche BlockLauncher zu starten kommt da nur weiß Bild. Ich hab dann gesehen dass Minecraft die Version 0.15.1 hat aber BlockLauncher die Version 1.12.8. Müssen die auf der gleichen Version sein? Wenn ja, wie mach ich dann das?

**Comment by zedman2000** [comment]
I can offer that if you have updated Minecraft to 0.15, that is why.  BlockLauncher does not support 0.15 yet.  Please close this so we do not have to sort this later.  The issue is being worked on.
Check twitter and you'll see that he is having issues with OpenGL and closing the app as well as a few more things.  What should have been a week has gotten much longer.  Please close this issue so the author does not have to sort this out later.

**Comment by RetrocrafterHD** [comment]
OK thx
