### ISSUE TITLE
Is Thare An Official Release Date For The Update?

### ISSUE THREAD

**Issue by lowjames** [zhuowei/MCPELauncher#1202]
Do you guys have an official release date for the update?

**Comment by zedman2000** [comment]
@lowjames you can welcome to follow zhuowei on twitter.  That generally is the first place that gets any announcement of release.  That is where I get all the information that I use to try to alert people to what is going on.  As of this post, there have been 3 beta releases that I am aware of.  None seem close enough to be called something you could take out of beta.  There have been a lot of issues with OpenGL.  One of the betas did finally allow you to script in diamonds - but nothing else seemed to work at this time.  I also am aware that there have been some big issues surrounding Armor.  I do not remember the details, but I do know that was specifically removed from the betas due to the issues that need to be overcome.

**Comment by lowjames** [comment]
@zedman2000  how do I download the beta release on a Amazon Fire?

**Comment by zedman2000** [comment]
@lowjames I would not recommend that.  Even Zhuowei has been posting them saying something to the effect of: I wouldn't use this...it's very broken.

To quote Zhuowei: "This beta is completely useless: do not download unless you're insane or something."

If you dare:
http://zhuoweizhang.net/MCPELauncher/

Also, be responsible.  Please do not install this, then say things do not work, unless you are ACTUALLY beta testing - not just messing about with it.  This means, you are FULLY aware of EVERYTHING that has been posted about and that you are NOT making more duplicate issues.

**Comment by lowjames** [comment]
Thx!

**Comment by zedman2000** [comment]
@lowjames can you please close this issue, as it is not really an issue?  Thanks.

**Comment by lowjames** [comment]
Fair enough
