### ISSUE TITLE
xlarge Russian translation

### ISSUE THREAD

**Issue by MelomanCool** [zhuowei/MCPELauncher#122]
Please add Russian translation for big screens to Languages menu.

**Comment by captphrank** [comment]
My Granddaughter is really good at MCPE.. she has a Samsung tablet...all of
a sudden her MCPE is gone and it wont download again. is this because she
doesn't have an Amazon Fire tablet. When I try to download the game it says
MCPE wont load on my device? I'm not asking anyone to fix it or tell me how
to fix, I just want to know why all of a sudden she can't play anymore, and
if I buy her an Amazon Tablet will she be able to play again. Shes 8
BTW...Thank You.
captphrank
