### ISSUE TITLE
why did I pay for this

### ISSUE THREAD

**Issue by cookmonster** [zhuowei/MCPELauncher#1320]
Why did the hell did I pay for block luncher pro for it not to be updated 0.15.2.1 is out but not block luncher

**Comment by ck1988** [comment]
They are working on the update as it is not fully functional with the 0.15 update of Minecraft pocket edition

**Comment by cookmonster** [comment]
I dont care I would beta test for them if they want

**Comment by zedman2000** [comment]
@cookmonster Now that you have your path forward, please close this so that the author does not have to spend the time closing this...I'd rather he work on finishing BL, instead of closing issues that have been reported a rather alarmingly large amount of times, instead of people reading what has been posted, then just adding to EXISTING issues.  Doing so shows the IMPORTANCE of an issue, instead of watering things down to the point of everything becomes noise and NO ONE gets any help.
