### ISSUE TITLE
You fucking idiots you must make a confatybility with new versions of minecraft

### ISSUE THREAD

**Issue by 111ukasz111** [zhuowei/MCPELauncher#1357]
For versions
0.15.X

**Comment by zedman2000** [comment]
Do you really think swearing is going to get you anything any faster?  If you took the time to read ANYTHING in here, you would see that it is being worked on.  You are free to NOT use the software if it causes you that kind of pain that you must try to lash out at someone for no reason other than you do not have any patience nor take ANY time to see what is going on before making accusatory remarks.

**Comment by captphrank** [comment]
You were right Mr. Rozwood, people don't listen. I've explained this to
others as you have and they keep writing back "it doesn't WORK"...and now
this guy is swearing at you!. What a Jack ass...Everybody wants it RIGHT
NOW, and act as if the Mod makers work for them..This 111uk1sz111 guy, does
NOT pay your wages or pay your rent.You owe him NOTHING!

**Comment by jose-vm** [comment]
LMAOO

**Comment by Black-DeathPE** [comment]
I could respond to the OP, but then I'd probably start swearing etc... This is hilarious tho, xD

**Comment by Black-DeathPE** [comment]
Changed my mind about not responding...

Tell me, why do you think @zhuowei hasn't updated BlockLauncher yet? Hm? Well, maybe you could've considered that he might be BUSY? You forget that this app is something he VOLUNTARILY made for the community and it is HIS choice to update it. In my opinion I think the reason he's not updated the app is because people like you are getting impatient and cussing at him and being overall disgusting. Don't you think he'd be put off if he saw constant people demanding him to update it and swearing? Wouldn't you? Have some patience and maybe, just maybe, you can look at the 11 PAGES OF THE SAME ISSUE BEFORE YOU MAKE ANOTHER? Next time you're about to complain, maybe think about not insulting them? Oh, sorry I forgot! This ISSUE TRACKER is an insult submitter! That makes sense!

Have a good day. I don't want to see you on this issue tracker again unless you have a valid thing to report.

**Comment by captphrank** [comment]
Well said...

**Comment by atn2001** [comment]
Have you tried searching for the beta before you go and demand for an updated version you retard.

**Comment by zhuowei** [comment]
f**k me.
f**k me.

I've spent a month and 20 days doing what can be done in a week. In the meantime even Toolbox has updated twice. I'm a f**king idiot and I don't deserve to be in charge of anything.

I know I'm the worst developer in the world. I know this. You don't have to tell me.

**Comment by ISAAC300** [comment]
'-' ;-;

**Comment by DiegoGTRatty** [comment]
All in favor of swatting uskaz say I.






























jk dont take this seriously

**Comment by SeeGreatness** [comment]
I
