### ISSUE TITLE
Suggestion:make a MCPE UI api for ModPE

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#1444]
:/ just thinking

**Comment by SaccyScriptor** [comment]
This should not be in the issues section. Java UI classes are perfectly normal. They would definitely give more options and freedom unlike a special API.

**Comment by zedman2000** [comment]
Check out Desno365's stuff.  He basically gives you an API for buttons and if I am remembering, other stuff.  There is also someone else (I cannot remember) that has created an API for menus.

Or just make your own.  Googling for examples, I came up with a GUI for my mod in about 2 hours.

**Comment by like2omg** [comment]
Just pointing out that such a task is highly error-prone if someone doesn't have each and every Android OS to test with, or (extremely common) the time to keep up-to-date with the changes, fixing their code, making sure it runs correctly on *all* the OS versions, fixing any new problems that shown up (which can happen on an OS version that the original problem didn't happen), repeating that until they assume they fixed it or they give up and vanish from the internet because of all the people asking, complaining, or demanding an update as if everything is given to them on a silver platter... ..... **It's just chaos!**

If you really understand what I'm saying, you would know how difficult it is to provide support for numerous Android versions that each have a different set of classes that are available, deprecated (otherwise known as "obsolete; do not use; will be removed in a future version" in the developer realm), and even ones that no longer exist (ever tried to run a game that was made specifically to only run in DOS in the days long ago where you only had Windows ME available? It's impossible! ... DOSBox didn't even exist back then...)

**Comment by zedman2000** [comment]
@like2omg you could run DOS games under Windows ME.  That was a fancy Windows 98SE, which has a DOS mode.  I'm assuming you are too young to have actually used that OS?  ;-)
Secondly, DOSBOX did exist back then.  It just wasn't very good as it was JUST starting out.
DOSBOX Initial Public Release July 22, 2002
Windows ME general availability June 19, 2000

Aside from the above dates, I have nothing but memory to tell you that I have used DOSBOX under Windows ME.  I just found it was easier to just make DOS MODE boot disks, or in most cases just shutdown to DOS and enough stuff was loaded to run games, but for the most annoying of games (where a customized boot disk would work).  Also, Windows 2000 and Windows XP were RIGHT on the horizon so a not so good and seemingly bloated WinME was quickly replaced with Windows 2000.  How nice!  The best part was, the boot disks still worked - so long as you did not convert your drive to NTFS.  I still remember the stack of disks I had to allow me to play certain games.  Crazy times!

Lastly, yes, it is DISK, as that is short for diskette, vs the more modern DISC, which is for CDROM DISCS.  ;-)

Party on Garth!  Party on Wayne!

**Comment by like2omg** [comment]
@zedman2000 Thank you for reminding me (I blame my memory issues). I even forgot ... oh my... I just remembered Qbasic / QuickBASIC (and part of my days using Win3.1 on a non-networked, home computer).
... Thank you for the memories that you triggered. *happily sighs*
