### ISSUE TITLE
32x32 Texture packs doesn't work

### ISSUE THREAD

**Issue by Rattlehead117** [zhuowei/MCPELauncher#570]
Some textures looks glitched like doors and similar

**Comment by Rattlehead117** [comment]
![screenshot_2016-01-29-21-42-02](https://cloud.githubusercontent.com/assets/16968436/12693504/2eea4f36-c6d1-11e5-8ff9-2cdaf712095a.png)
Happens in all builds

**Comment by Black-DeathPE** [comment]
This is an incompatibility down to MCPE unfortunately, since MCPE is designed to only use the default 16x textures. Some parts are compatible with higher resolution, but things such as items are not. This might be tedious for Zhuowei to fix, but at least when they finally add texture packs in general it'll be fixed :)

**Comment by Rattlehead117** [comment]
Thanks :)
