### ISSUE TITLE
Custom Named Texture Doesn't Work in modpkg

### ISSUE THREAD

**Issue by officialmcpro32** [zhuowei/MCPELauncher#638]
@zhuowei this bug is still in BL where custom named textures doesn't work

**Comment by zhuowei** [comment]
@officialmcpro32 example modpkg, please?

**Comment by officialmcpro32** [comment]
http://www.mediafire.com/download/k4j4zi2rbb956fq/Example_for_Zhuowei.modpkg
@zhuowei there

**Comment by zhuowei** [comment]
Oh, I see what's probably happening:
- ModPkg imported
- Script tries to load texture
- Fails since texture packs need a reboot
- Script gets disabled

Will fix by checking if ModPkg contains items/terrain data, and if so force a restart after import without disabling the script in-between. Good catch!

**Comment by officialmcpro32** [comment]
@zhouwei so can you fix it? I'm pretty sure there's a way for texture packs to load without restart

**Comment by officialmcpro32** [comment]
@zhuowei for me the point of modpkg is without having to install and restart texture packs with mod

**Comment by zhuowei** [comment]
Fixed: currently it listens for "texture missing" errors when importing a ModPkg, and if found restarts the launcher instead of disabling the script.

**Comment by officialmcpro32** [comment]
@zhuowei thanks when is the next beta? Also the custom liquids
