### ISSUE TITLE
When I open my world and break a block in block launcher. It keeps crashing. Please help me fix thid or I rate 1 star on Google play

### ISSUE THREAD

**Issue by timberstar** [zhuowei/MCPELauncher#774]

**Comment by timberstar** [comment]
Sorry I wrote in the title box on accident XD

**Comment by zedman2000** [comment]
@timberstar probably should try asking a proper question and giving some information about WHAT you are doing to break the block, instead of threatening a "1 star" rating.  I think most on here would be happy to help you - but DEMANDING like that makes most of us NOT want to help you.  It is not very nice.  You did not even tell anyone what phone you have, what version of MCPE / BL, what scripts you have, what maps you are using, etc.  More than likely it is something you are doing to your device that is causing this since most of us (everyone else?) does not have this same issue and we would need to troubleshoot the issue.

**Comment by zedman2000** [comment]
Also, this gentleman seems to have a similar issue and you can see how he got a response.  Just a tip for the future.  :-)
https://github.com/zhuowei/MCPELauncher/issues/763

Try rebooting?  (read the linked issue, that's all that person did to resolve the issue)
